name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # or master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: shashigcp-454502
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/shashigcp-454502/gh-demo/flask-app:latest .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/shashigcp-454502/gh-demo/flask-app:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flask-app \
            --image=us-central1-docker.pkg.dev/shashigcp-454502/gh-demo/flask-app:latest \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated
