name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: shashigcp-454502
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Authenticate Docker to Artifact Registry
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/shashigcp-454502/gh-demo/flask-app:latest .

      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/shashigcp-454502/gh-demo/flask-app:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flask-app \
            --image=us-central1-docker.pkg.dev/shashigcp-454502/gh-demo/flask-app:latest \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated
